name: My test
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        if: github.actor == 'gitKatJ'
        run: echo "Triggered by $GITHUB_EVENT_NAME event on branch $GITHUB_REF"
      - name: Run a multi-line script
        if: github.actor == 'gitKatJ'
        run: |
          echo "Add other actions to build"
          echo "test, and deploy your project"